groups:
  - name: web-alerts
    rules:
      - alert: WebDown
        expr: probe_success{job="blackbox-http"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "La web no responde (health.php)"
